### ISSUE TITLE
 Different results when using 3 providers instead of 2

### ISSUE THREAD

**Issue by eSkRo32** [mancuniancol/plugin.video.cpasbien#1]
Not sure if this has been talked already as i can't seem to find anything on it.

in Quasar, if using strictly 3 providers instead of just 2,
result listed aren't the same as when using 3 providers...

example, cpasbien is not listing everything i noticed...

noticed this when using these 3
- pirate bay
- kick ass
- cpasbien

using those 3 at the same time,
cpasbien shows very few results to download/watch

but when using just piratebay and cpasbien
meaning you uninstall kick ass or disabled it which ever,
cpasbien shows far greater results to download/watch.

normal or??

thanks guys!!

**Comment by mancuniancol** [comment]
This is not Quasar provider.
